# **********Docker Compose file*********#
# version: '3.8'
# services:
#   disney-hotstar:
#     build:
#       context: .
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_OPTIONS=--openssl-legacy-provider


# **********Multistage Docker Compose file***********#
version: '3.8'
services:
  disney-hotstar:
    build:
      context: .
      dockerfile: jenkinsDockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
