---
- name: Pull Kubernetes manifest files
  hosts: k8s-server  
  tasks:
    - name: Copy Kubernetes manifest files to the Node server
      copy:
        src: "/var/lib/jenkins/workspace/{{ lookup('env', 'pipeline_name') }}/{{ item }}"  # Use environment variable for pipeline_name
        dest: "/root/k8s-manifest/{{ item }}"
      with_items:
        - k8s-deployment-service.yaml
